# Generated by Django 3.1.5 on 2021-01-20 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_members_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='members',
            options={'verbose_name': '오픈튜토리얼스 사용자', 'verbose_name_plural': 'o2 사용자'},
        ),
    ]
